name: sqlite_demo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # utilities
  dartz: ^0.10.1
  collection: ^1.16.0
  intl: ^0.17.0
  uuid: ^3.0.7
  path: ^1.8.2
  path_provider: ^2.0.11
  connectivity_plus: ^3.0.2
  flutter_dotenv: ^5.0.2

  # Routes and navigation
  auto_route: ^5.0.4

  # Local cache
  floor: ^1.3.0
  sqflite: ^2.2.2
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.1.0

  # http client
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

  # Data class and union class
  freezed_annotation: ^2.2.0

  # Json annotation for serializable
  json_annotation: ^4.7.0

  # Riverpod for state management and providers
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.18.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.2
  floor_generator: ^1.3.0
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.2
  freezed: ^2.2.0

# derry
scripts: derry.yaml

# import_sorter
import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/\w.g.dart\/*
    - \/\w.gr.dart\/*
    - \/\w.freezed.dart\/*
    - \/\w.gen.dart\/*

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/database/Armo.db
